// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4w1bPGAfMqeNqes7RLgK9QzzihmfxD6g',
    appId: '1:822306796449:web:4833c4ccc7a18ac8a611e0',
    messagingSenderId: '822306796449',
    projectId: 'chatapptest-200ac',
    authDomain: 'chatapptest-200ac.firebaseapp.com',
    storageBucket: 'chatapptest-200ac.appspot.com',
    measurementId: 'G-LZEH09Z0MK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADDz8kJumj3Hudv67dRPdUH6vi4Lh0mKM',
    appId: '1:822306796449:ios:328f9080dcd7c65ea611e0',
    messagingSenderId: '822306796449',
    projectId: 'chatapptest-200ac',
    storageBucket: 'chatapptest-200ac.appspot.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4w1bPGAfMqeNqes7RLgK9QzzihmfxD6g',
    appId: '1:822306796449:web:c715295f131eb379a611e0',
    messagingSenderId: '822306796449',
    projectId: 'chatapptest-200ac',
    authDomain: 'chatapptest-200ac.firebaseapp.com',
    storageBucket: 'chatapptest-200ac.appspot.com',
    measurementId: 'G-959V1DNM7N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDz8kJumj3Hudv67dRPdUH6vi4Lh0mKM',
    appId: '1:822306796449:ios:328f9080dcd7c65ea611e0',
    messagingSenderId: '822306796449',
    projectId: 'chatapptest-200ac',
    storageBucket: 'chatapptest-200ac.appspot.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB6qesuhNpf6ECt0elgAOkpntHdgyGbv8',
    appId: '1:822306796449:android:9cffa9a9b2ba66f7a611e0',
    messagingSenderId: '822306796449',
    projectId: 'chatapptest-200ac',
    storageBucket: 'chatapptest-200ac.appspot.com',
  );

}